### ISSUE TITLE
Не получаю сообщения из ВК

### ISSUE THREAD

**Issue by ca5ua1** [progserega/MatrixVkBot#31]
Зато есть такая ошибка
`  "body": "ошибка получения сообщений из ВК. Ошибка работы с ВК-апи в функции get_new_vk_messages_v2()",`

**Comment by serega404** [comment]
> 
> 
> Зато есть такая ошибка ` "body": "ошибка получения сообщений из ВК. Ошибка работы с ВК-апи в функции get_new_vk_messages_v2()",`

Какой access token использовали?

**Comment by ca5ua1** [comment]
`vk_app_id="2685278"   #"2274003"`
Пробывала эти оба, должны быть от Kate mobile

**Comment by serega404** [comment]
Попробуйте убрать кавычки `"`
Что бы получилось: `vk_app_id=2685278`

**Comment by ca5ua1** [comment]
Отсутствие кавычек - не помогло. Всё удалила, кроме config.py, и склонировала репозиторий. 
Прошла авторизацию, добавила новый диалог, попыталась в него написать и словила это

```
2021-10-22 16:59:31,673 - MatrixVkBot - bot.py:1674 - on_message() DEBUG - =start function=
2021-10-22 16:59:31,673 - MatrixVkBot - bot.py:1681 - on_message() DEBUG - new MATRIX message:
2021-10-22 16:59:31,673 - MatrixVkBot - bot.py:1682 - on_message() DEBUG - {
    "content": {
        "body": "test",
        "msgtype": "m.text"
    },
    "event_id": "тут_был_текст",
    "origin_server_ts": тут_был_текст,
    "room_id": "тут_был_текст",
    "sender": "тут_был_текст",
    "type": "m.room.message",
    "unsigned": {
        "age": 317
    }
}
2021-10-22 16:59:31,673 - MatrixVkBot - bot.py:1734 - on_message() DEBUG - тут_был_текст: test
2021-10-22 16:59:31,673 - MatrixVkBot - bot.py:1735 - on_message() DEBUG - try lock before process_command()
2021-10-22 16:59:31,673 - MatrixVkBot - bot.py:1737 - on_message() DEBUG - success lock before process_command()
2021-10-22 16:59:31,673 - MatrixVkBot - bot.py:58 - process_command() DEBUG - =start function=
2021-10-22 16:59:31,673 - MatrixVkBot - bot.py:101 - process_command() DEBUG - user=@casul:matrix.org send command=test
2021-10-22 16:59:31,673 - MatrixVkBot - bot.py:102 - process_command() DEBUG - cur_state=dialog
2021-10-22 16:59:31,674 - MatrixVkBot - bot.py:356 - process_command() ERROR - Traceback (most recent call last):
  File "/тут_был_текст/MatrixVkBot/./bot.py", line 106, in process_command
    bot_control_room=data["users"][user]["matrix_bot_data"]["control_room"]
KeyError: 'matrix_bot_data'

2021-10-22 16:59:31,674 - MatrixVkBot - bot.py:357 - process_command() ERROR - exception at execute process_command()
2021-10-22 16:59:31,674 - MatrixVkBot - bot.py:1165 - bot_system_message() DEBUG - =start function=
2021-10-22 16:59:31,674 - MatrixVkBot - bot.py:1166 - bot_system_message() INFO - внутренняя ошибка бота при обработке команды в функции process_command()
2021-10-22 16:59:31,674 - MatrixVkBot - bot.py:1173 - bot_system_message() ERROR - Traceback (most recent call last):
  File "/тут_был_текст/MatrixVkBot/./bot.py", line 106, in process_command
    bot_control_room=data["users"][user]["matrix_bot_data"]["control_room"]
KeyError: 'matrix_bot_data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/тут_был_текст/MatrixVkBot/./bot.py", line 1167, in bot_system_message
    bot_control_room=data["users"][user]["matrix_bot_data"]["control_room"]
KeyError: 'matrix_bot_data'

2021-10-22 16:59:31,674 - MatrixVkBot - bot.py:1174 - bot_system_message() ERROR - exception at execute bot_system_message()
2021-10-22 16:59:31,674 - MatrixVkBot - bot.py:1748 - on_message() ERROR - error process command: 'test'
```

**Comment by progserega** [comment]
Попробуйте удалить (переместить) файл статуса бота - его путь задаётся в конфиге в опции `data_file`

**Comment by ventureoo** [comment]
Аналогичная проблема.
